//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderMgmtService.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public System.Guid BuyerId { get; set; }
        public string BuyerName { get; set; }
        public string BuyerLocation { get; set; }
    }
}
