//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderMgmtService.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_UserSession
    {
        public System.Guid Token { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual Security_User Security_User { get; set; }
    }
}
