//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderMgmtService.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDetail
    {
        public string Order_No { get; set; }
        public string PO_No { get; set; }
        public string Invoice_No { get; set; }
        public System.DateTime Shipping_Date { get; set; }
        public decimal Weight { get; set; }
        public System.Guid ShippedById { get; set; }
        public System.Guid ShippingModeId { get; set; }
        public Nullable<System.DateTime> Advised { get; set; }
        public string Consigned_To { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual ShippingMode ShippingMode { get; set; }
        public virtual Order Order { get; set; }
        public virtual ShippedBy ShippedBy { get; set; }
    }
}
